### ISSUE TITLE
This projects appears to be outdated and not maintained.

### ISSUE THREAD

**Issue by lipis** [coto/gae-boilerplate#318]
hey @coto.. I have a similar boilerplate project for App Engine and since this project is a bit outdated.. do you think it would make sense to redirect the users to a more up to date project as an alternative?

We could have a note on top of the README stating that it's outdate and possible alternative could be the [gae-init](https://github.com/gae-init/gae-init)..

What do you think?

**Comment by coto** [comment]
Hi @lipis I just added a link to Flask Biolerplates that people have been asking. Where it is yours.

Kind

**Comment by lipis** [comment]
Thank you.. I just want to mention that the other projects are also outdated and not very much maintained..
