### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by alexandernst** [coto/gae-boilerplate#319]
I'm searching for a stable base for a project I'll be working on and this project draw my attention. It has a lot of features, but I also see quite some bugs and no commit activity.

What is the state of the project?

**Comment by peterretief** [comment]
It worked for a project a year ago, I haven't looked at it recently

**Comment by coto** [comment]
@alexandernst this project is for webapp2 in Google app engine. It does not mean is is outdated.

**Comment by alexandernst** [comment]
@coto Does it? I do see some open issues about outdated third party libraries. I also see some references to some sort of refactoring or `new structure` of the project (https://github.com/coto/gae-boilerplate/issues/295), but I haven't seen anything tangible on that subject.

**Comment by lipis** [comment]
@coto let's be honest.. in the last 2 years there are no real updates and with the web technlogies.. things are moving quite fast.. jQuery released version 3.. Modernizer as well.. Bootstrap latest stable is 3.3.6 and 4 is it's way and this is just scratching the surface of what is visible from your README file.. Did you notice that the _sponsored_ image is broken? I'm not judging on why (most likely you have better things to do) but I think it's fair to point somewhere this project **is outdated** and starting something new with it.. is really not recommended in 2016..

I own [gae-init](https://github.com/gae-init/gae-init) and know what it takes to keep everything up to date.. and so far it's the only Python GAE framework/boilerplate that is actually up to date (well tested, etc, etc.) 

So if you really care about the users just update it or say something about the state of the project in the README..

**Comment by coto** [comment]
thanks @lipis for you comment. I just updated the README file to show this is a legacy project and below are link to modern projects like gae-init.

Kind regards
